### ISSUE TITLE
Changed prefix, but didnt changed on help

### ISSUE THREAD

**Issue by reiven** [embolalia/willie#389]
Hi, i've change the "prefix" settings from "." to "!" but on the commands help, it stills shows the "original prefix" instead of the new one

example:

<reiven> !help g
<nataraja> reiven: Queries Google for the specified input.
<nataraja> e.g. .g swhack

Maybe it should existe a "bot.prefix" for this cases?

**Comment by embolalia** [comment]
Added config.core.help_prefix in ddb8a5421654dae31d2fbc18865c26dd21b9caf2 to let it be changed.
