### ISSUE TITLE
DNS Record Lookups

### ISSUE THREAD

**Issue by WireShout** [embolalia/willie#422]
Willie should be able to preform DNS lookup queries.

Syntax: .dns record_type hostname

record_types should be those that are listed at http://en.wikipedia.org/wiki/List_of_DNS_record_types, but A, AAAA, CNAME, MX, TXT, and SPF should be supported at least.

hostname should just be the fully qualified hostname. (ex: example.com, what.on.earth.is.this.foobar.net, etc.)

**Comment by elad661** [comment]
I think I'll go ahead and close this issue. It has been open since 2014 and nobody else wanted similar functionality in Willie. 

Just open up a terminal and use `dig`.

If anyone want to implement such module, go ahead, but I honestly don't think it fits within the core module set.
