### ISSUE TITLE
Check If authed with Nickserv in modules ( admin module )

### ISSUE THREAD

**Issue by davidmann4** [embolalia/willie#454]
Is there any chance to enable authed users with nickserv? Otherwise it is not very secure.

/msg NICKSERV acc username 

returns the user state of the user

can you guide me how I can add this functionality to the bot?

**Comment by embolalia** [comment]
NAK, as far as including this in the main project is concerned. Not sure why I didn't close this earlier; integration with various NickServs beyond authing the bot itself has never been something we consider inside our scope.
