### ISSUE TITLE
[chanlogs] exceptions with channels that have "/"

### ISSUE THREAD

**Issue by bui** [embolalia/willie#490]
````
Traceback (most recent call last):
  File "/home/amphy/willie/willie/bot.py", line 747, in call
    exit_code = func(willie, trigger)
  File "/home/amphy/willie/willie/modules/chanlogs.py", line 115, in log_join
    with open(fpath, "a") as f:
IOError: [Errno 2] No such file or directory: u'/vp/-2014-03-21.log'
````

I imagine there'll be issues with other characters too, so what can be done about this? I believe ZNC's log module replaces special characters with a `?` or `_`, maybe this should be done here?

**Comment by embolalia** [comment]
I like the idea of URL encoding, although I don't know whether that would play well serving the log dir over http. Would they end up double-encoded? Still, probably better to just do something to stop the errors, even if there's a better way.

**Comment by mshade** [comment]
As much as I hate suggesting this, I think perfect is the enemy of good in this case, and translating "illegal" characters to something common is probably the best approach. The other alternative would be  logging to a database by default, or using a checksum of some sort, which both lead to awful discoverability.

Perhaps use something like __ (double underscore) as the substitution? Be very conservative in which "illegal" characters would trigger it.
