### ISSUE TITLE
Unicode equal comparison failed to convert both arguments to Unicode with rss.py

### ISSUE THREAD

**Issue by N3bTcx** [embolalia/willie#543]
Hello

I'm getting an error with the last version of Willie (version ﻿[8cd3bef](https://github.com/embolalia/willie/commit/8cd3bef40c5e3a507c76352f6c09ad542734a696))
`/usr/local/lib/python2.7/dist-packages/willie/modules/rss.py:449: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if (feed.title == entry.title and feed.link == entry.link`

Thanks

**Comment by embolalia** [comment]
RSS module is removed in 6.0 and is no longer maintained, per #818. Closing.
