### ISSUE TITLE
Shorten RSS URLs with tinyurl/bit.ly

### ISSUE THREAD

**Issue by tuxillo** [embolalia/willie#558]
Hi,

Would it be possible that the bot reported RSS URLs with bit.ly or tinyurl instead of a long URL?

Example:
[gitweb-dports] Import lang/nimrod version 0.9.2_1
http://gitweb.dragonflybsd.org/dports.git/commitdiff159c5a1384657cd2b0402e97d34f2de9a2573962 - 2014-06-25 - 22:01:04

Would be:
[gitweb-dports] Import lang/nimrod version 0.9.2_1
http://bit.ly/1qi9CVV - 2014-06-25 - 22:01:04

Thanks,
Antonio Huete

**Comment by rinzes** [comment]
tinyurl does not have a oauth token and is free. It would be really nice if you would add this feature

**Comment by embolalia** [comment]
RSS module is removed in 6.0 and is no longer maintained, per #818. Closing.
