### ISSUE TITLE
backports.ssl_match_hostname is not in the pip dependencies

### ISSUE THREAD

**Issue by IRCWillie** [embolalia/willie#661]
Submitted by: Embolalia
From channel: #tech
At 2014-11-20 02:58:44 UTC

**Comment by embolalia** [comment]
The bot should now connect without needing the dependency, but will not allow SSL (same as if the `ssl` module itself is not available). Requests through `willie.web` that try to verify SSL will fail and give an error.

It's still a problem, though, that this isn't getting picked up in pip installs. I haven't the slightest bit of an idea of what a clue might even be as to why this is happening, though.

**Comment by pmrowla** [comment]
I think the problem is that pip looks for `install_requires` not `requires` in setup.py

http://stackoverflow.com/questions/12372336/how-do-i-make-pip-respect-requirements
