### ISSUE TITLE
How does color [fg] [bg] work in rss?

### ISSUE THREAD

**Issue by bhavyanshu** [embolalia/willie#679]
Can you please put an example in the documentation or help text as to how this works? 
Also it is showing `DeprecationWarning`

    DeprecationWarning: To avoid breaking existing software while fixing issue 310, a temporary mapping has been created from `updated_parsed` to `published_parsed` if `updated_parsed` doesn't exist. This fallback will be removed in a future version of feedparser.

**Comment by embolalia** [comment]
RSS module is removed in 6.0 and is no longer maintained, per #818. Closing.
