### ISSUE TITLE
Rewrite rss module from scratch

### ISSUE THREAD

**Issue by embolalia** [embolalia/willie#693]
It is, was, and always has been a buggy mess. It should be replaced, since that would close #679, #605, #573, #543, #537, #514, and optionally #583 and #558. (I'm not closing them now, because I *suppose* someone might want to address them before anyone gets around to actually dong this. Given that #194 was open for nearly two years, this might be a while.)

**Comment by rinzes** [comment]
Here is a temp patch to use url shortner until the module is rewritten. http://pastebin.com/fMJLJkj2

**Comment by embolalia** [comment]
RSS module is removed in 6.0 and is no longer maintained, per #818. Closing.
