### ISSUE TITLE
Error using .setlocation when a previous location is already set

### ISSUE THREAD

**Issue by djahren** [embolalia/willie#697]
When a user enters a new location using .setlocation when they already have one set they get the following error: 

<@Willie> ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 2 supplied. (file "/home/willie/jenni/willie/db.py", line 685, in update)

**Comment by StygianTraveler** [comment]
Same issue here, and it doesn't apply only to the locations. It seems like trying to set any user value gives this error if the user is already in the database. Say, you .setlocation for the first time, it works fine. Then the same user tries to .settz, nope, error.

I'm not sure when this popped up exactly, it used to work fine, but I tried reverted to an older Willie version and still get an error... Weird. Maybe it's a problem with my database file?

**Comment by embolalia** [comment]
This issue is resolved by the 5.0.0 release.
