### ISSUE TITLE
Fresh install errors

### ISSUE THREAD

**Issue by undernocircumstance** [embolalia/willie#698]
Set up a fresh copy of 4.6.2 (downloaded zip from github: "Willie v. 4.6.2-git at unknown commit") and getting the following error when using tell or weather for example:

<williebot> OperationalError: near "<": syntax error (file "/opt/willie462/willie/db.py", line 761, in contains)

Traceback:

Traceback (most recent call last):
  File "/opt/willie462/willie/bot.py", line 743, in call
    exit_code = func(willie, trigger)
  File "/opt/willie462/willie/modules/tell.py", line 112, in f_remind
    tz = willie.tools.get_timezone(bot.db, bot.config, None, tellee)
  File "/opt/willie462/willie/tools.py", line 556, in get_timezone
    if not tz and nick and nick in db.preferences:
  File "/opt/willie462/willie/db.py", line 770, in __contains__
    return self.contains(item)
  File "/opt/willie462/willie/tools.py", line 290, in new
    return old(*args, **kwargs)
  File "/opt/willie462/willie/db.py", line 761, in contains
    cur.execute('SELECT * FROM ' + self.name + ' WHERE ' + where, [row])
OperationalError: near "<": syntax error

Bot has no special characters in its name.

Python 2.7.8 on Fedora 21.

Pip freeze (dependencies):

feedparser==5.1.3
pytz==2014.10
lxml==3.4.1
praw==2.1.19
pyenchant==1.6.6
pygeoip==0.3.2

**Comment by undernocircumstance** [comment]
Checked out 4.6.1 and got the same error, checked out 4.5.1 and the problem is gone.

**Comment by MDFowler** [comment]
I'm getting a different traceback error off of a fresh install. This is on a Raspbian system where I'm using ssh to control my raspberry pi. Used pip to install and tried doing `python ~/build/willie/willie.py` as the command as just typing `willie` like the tutorial doesn't work.

>Traceback (most recent call last):
>  File "willie.py", line 29, in \<module>
>    from willie.config import Config, create_config, ConfigurationError, wizard
>  File "/home/ircbot/build/willie/willie/config.py", line 52, in \<module>
>    import willie.bot
>  File "/home/ircbot/build/willie/willie/bot.py", line 26, in \<module>
>    import willie.irc as irc
>  File "/home/ircbot/build/willie/willie/irc.py", line 39, in \<module>
>    import backports.ssl_match_hostname
>ImportError: No module named backports.ssl_match_hostname

**Comment by tyrope** [comment]
@MDFowler Your comment is not at all related to the issue reported. Also, it is a very common issue easily solved: Install backports.ssl_match_hostname.

**Comment by MDFowler** [comment]
@tyrope Sorry, thought it was better than starting a new issue since they both involved fresh installs. Did find that and eventually got it to work, however that thread also said you had fixed it so I thought there was still an issue.

**Comment by nickperkins** [comment]
Occurs in 4.6.2 but at line 460

**Comment by nickperkins** [comment]
Confirm having same issue with version installed using pip

**Comment by embolalia** [comment]
This issue is resolved by the 5.0.0 release.
