### ISSUE TITLE
Reddit module posting two different summaries

### ISSUE THREAD

**Issue by RustyBower** [embolalia/willie#704]
19:54:10 <RustyCloud> https://www.reddit.com/r/movies/comments/2rn7yx/spectre_photocall_with_daniel_craig_lea_seydoux/
19:54:12 <RustyCloud> testing this
19:54:20 <RustyCloud> ....
19:54:21 <@BotSaget> [REDDIT] SPECTRE photocall with Daniel Craig, Lea Seydoux, and Dave Bautista on location in Austria (http://imgur.com/a/jTX7d/) to r/movies | 3682 points (3682|0) | 706 comments | Posted by GetFreeCash
19:54:24 <@BotSaget> [REDDIT] SPECTRE photocall with Daniel Craig, Lea Seydoux, and Dave Bautista on location in Austria (http://imgur.com/a/jTX7d/) to r/movies | 3682 points (92.0%) | 706 comments | Posted by GetFreeCash

This wasn't an issue on 4.6.1 (last release I was running), but appears to be an issue with 5.0.0-beta.

**Comment by embolalia** [comment]
Somehow, you have an old version of the module loaded. (Note how one of them gives upvote./downvote instead of percent, which that module no longer does since reddit dropped support for that). Do you have anything in `~/.willie/modules` (or any other extra directories)? Try removing .pyc files and restarting.

**Comment by RustyBower** [comment]
You are absolutely correct. As soon as you posted this I remembered I was running willie beta from a python setup.py install, instead of out of the directory (which I have been doing recently).

Sadly, in order to uninstall willie (for a new version or whatever), this is what I have to do:
python setup.py install --record files.txt
cat files.txt | xargs rm -rf

Is there a better way to uninstall willie to prep for an upgrade/new version?

**Comment by embolalia** [comment]
You could remove the directory from site-packages directly, but that way works too. Or you could just run it directly rather than installing it.
