### ISSUE TITLE
[help req] Am i doing something wrong?

### ISSUE THREAD

**Issue by judge2020** [embolalia/willie#730]
Sorry to bother you, but I feel i have left something out. I decided to follow the "part 2" of making a willie module, but I got stuck. I added an helloworld.py to my \modules folder and it DOES add 1 to the modules loaded count on startup, but when i say .helloworld my bot doesn't say Hello, world! back.
I have checked that I did set the owner as me with exact capitalization, even though i perceive this as a function that wouldn't require admin.

![](http://i.gyazo.com/00f57202cd5850927e15874f511367d3.png)

**Comment by embolalia** [comment]
It's an error in the wiki page. It should say `import willie.module`; I've fixed it.

**Comment by judge2020** [comment]
Thanks!

**Comment by judge2020** [comment]
hmm, seems saying .helloworld is still not working.

**Comment by tyrope** [comment]
Is your [core]prefix set to `\.`?

**Comment by tyrope** [comment]
Tested with the following code in `~/.willie/modules/helloworld.py`
```
import willie.module

@willie.module.commands('helloworld')
def helloworld(bot, trigger):
    bot.reply("hello, world!")
```
As expected:
```
[2333.41] <Tyrope> .helloworld
[2333.41] <Boomer> Tyrope: hello, world!
```

**Comment by judge2020** [comment]
i'm so sorry about this, i'm so stupid
the channel was +m :-1:
