### ISSUE TITLE
Implement filter decorators for maintainability and security

### ISSUE THREAD

**Issue by Factionwars** [embolalia/willie#731]
This code:
```python
    if not trigger.is_privmsg:
        return
    if not trigger.admin:
        return
```
In module functions this lead to repetitive code and possible security issues introduced by lousy programming. Because of this i propose the usage of filter decorators which are used throughout most python frameworks for restricting actions. Example:

```python
@willie.module.commands('quit')
@willie.module.priority('low')
@willie.filters.is_privmsg
@willie.filters.is_owner
def quit(bot, trigger):
    """Quit from the server. This is an owner-only command."""

    quit_message = trigger.group(2)
    if not quit_message:
        quit_message = 'Quitting on command from %s' % trigger.nick

    bot.quit(quit_message)
```
Where the filters can also have a optional error message which you can pass along to the decorator.

I might actually implement this here if people like it, otherwise we will do it for our own fork.

**Comment by merijntestroote** [comment]
I just noticed that there is already a @willie.module.require_privmsg decorator. This could be a start.

**Comment by embolalia** [comment]
Sounds good to me. I'd personally put them in `willie.module`, but the idea is fine.

**Comment by firerogue** [comment]
Personally I'm in favor of a `filters` group, but I agree with embolalia
that they should go under `willie.module`. However, since
`willie.module.filters` is pretty long, I'm not 100% sure what I think
should be done

**Comment by Factionwars** [comment]
I checked and there is already a require_privmsg decorator in the modules path. We can build it in that style first.

**Comment by dgw** [comment]
I'm in favor of the `willie.module.require_x` format, myself. :+1:

**Comment by tyrope** [comment]
:+1: for `willie.module.is_privmsg`
Question for the community: Would we need the `.is_chanmsg`/`.isnt_privmsg` counterpart? If so, which one?



As suggested above:
For channel privs: `willie.module.require_voice`, `willie.module.require_halfop`, `willie.module.require_op`
For Willie privs: `willie.module.require_owner`, `willie.module.require_admin`

My suggestion: (To lower the amount of different decorators while keeping functionality)
`@willie.module.access(level)` (name pending, suggestions welcome)
Valid values for level: None, willie.module.VOICE, willie.module.HALFOP, willie.module.OP (All of these already exist), willie.module.ADMIN, willie.module.OWNER (These would have to be added)

One potential problem being future support for +a &+q. But I don't think that's even remotely on the roadmap.

**Comment by firerogue** [comment]
Worst case we can change it to I_OP, I_VOICE, etc and W_OWNER, W_ADMIN if
we ever get there

**Comment by embolalia** [comment]
@tyrope Big +1 on using constants as an argument to the decorator! I don't think it should do admin and owner in the same decorator, though, since they wouldn't work with the bitwise operations, and as such would just confuse things.

**Comment by embolalia** [comment]
Done in 3feb82ab24891fd5a4a6449f3e7e64cba4fd4865.
