### ISSUE TITLE
KeyError: Adminchannel.py

### ISSUE THREAD

**Issue by rinzes** [embolalia/willie#734]
when I did .op dutch (willie is oped) I got the following error:
KeyError: Identifier('dutch') (file "/usr/local/lib/python2.7/dist-packages/willie/modules/adminchannel.py", line 34, in op)

**Comment by tyrope** [comment]
Please provide the information stated at the top of our [guidelines for contributing](https://github.com/embolalia/willie/blob/master/CONTRIBUTING.md).

**Comment by rinzes** [comment]
Here is the pertain info requested:

I am using willie v5.0 and was installed using pip. The OS is a shell using Debian v7.0 64bit

I was unable to get opped from willie when I did .op

see above for the return error

**Comment by tyrope** [comment]
Willie doesn't op if it's not op itself OR if the person issuing the .op command isn't op.

It should, however, not issue a KeyError.

**Comment by rinzes** [comment]
Please note above: willie (he was op)

**Comment by tyrope** [comment]
@rinzes `I was unable to get opped from willie (he was op) when I did .op`. I assume by this that you were not op, in which case Willie wouldn't let you op, this is to prevent channel takeovers.
