### ISSUE TITLE
Join a channel with key.

### ISSUE THREAD

**Issue by lkarsten** [embolalia/willie#738]
Hi.

I want to run willie on a password protected channel, but I can't find any way of configuring the key.

As far as I can see willie/irc.py's join() method support this, but willie/coretasks.py does not use it. 
I found a way of doing manual password protected joins via the admin.py module, but I need this to be automatic.

I'm running willie from git, ref aaaf6a21.

Please consider adding this feature.

**Comment by embolalia** [comment]
You mean on startup? Last I checked, you can put it in the config with a space between the channel and key (`#spam,#eggs bacon,#morespam`).

**Comment by embolalia** [comment]
Just checked, one of the instances on dftba.net does it that way, so it definitely works. Closing.
