### ISSUE TITLE
Weather Module looking at different table

### ISSUE THREAD

**Issue by distantstar** [embolalia/willie#741]
In Line 135 in the Weather module, it calls on the table channel_value but sqlite3 does not save the WOEID information in channel_value. I have noticed it saves WOEID in nick_value instead, thus whenever '.weather NICK' is invoked, it returns 'I don't know where that is.' Once the channel_value is changed to nick_value, it reads the WOEID properly and returns the correct information. I cloned the master for this message.

**Comment by tyrope** [comment]
If you've already made this edit, could you issue a pull request?

**Comment by distantstar** [comment]
I will do that.
