### ISSUE TITLE
Run willie in the background

### ISSUE THREAD

**Issue by judge2020** [embolalia/willie#743]
Right now i'm trying to have my bot continuously run on my ubuntu server. when i run willie, i t works correctly but it is not forced into the background. this means that i cannot leave the bot  running if i close that terminal session. Also since putty sessions time out, i can't just leave my home computer running. 

is there a way to send it into the background?

**Comment by tyrope** [comment]
Run willie with -d, as explained [here](https://github.com/embolalia/willie/wiki/Command-Line-Arguments)
