### ISSUE TITLE
Willie newbie on his Debian stable with some module problems.

### ISSUE THREAD

**Issue by antdude** [embolalia/willie#748]
Hello.

...
Welcome to Willie. Loading modules...

Error loading twit: No module named tweepy (../../../../../../home/ant/.willie/modules/twit.py:10)
Error in helpbot setup procedure: 'Config' object has no attribute 'helpbot' (config.py:203)
Error loading currency: No module named lxml (modules/currency.py:11)
Error loading weather: No module named lxml (modules/weather.py:16)
Error loading spellcheck: No module named enchant (modules/spellcheck.py:13)
Error loading dicelog: cannot import name calculate (../../../../../../home/ant/.willie/modules/dicelog.py:15)
Error in ai setup procedure: 'Config' object has no attribute 'ai' (config.py:203)
Error loading bucket: No module named MySQLdb (../../../../../../home/ant/.willie/modules/bucket.py:37)
Error in document setup procedure: 'Config' object has no attribute 'document' (config.py:203)
Error in redmine setup procedure: 'Config' object has no attribute 'redmine' (config.py:203)
Error loading bugzilla: No module named lxml (modules/bugzilla.py:11)
Error in imgur setup procedure: 'Config' object has no attribute 'imgur' (config.py:203)

Registered 51 modules,
12 modules failed to load
...

How do I fix these so these modules will work on my Debian stable? Thank you in advance. :)

**Comment by janandjohn3** [comment]
Some of the modules you downloaded have dependencies that Willie core
doesn't need and doesn't download. You need to install the following
modules:
tweepy, lxml, enchant, MySQLdb.
You can install these easily using pip:
sudo pip install tweepy lxml enchant MySQLdb

Most of the other errors are telling you that the module cannot start
because of it not having its configuration section in the config file. You
probably will need to check where you got the module for help. If you can't
find any help for that, I can look through the code and help you figure out
the configuration options that it requires.

>

-- 
John Lage

**Comment by antdude** [comment]
I removed the extra modules and retried:

Welcome to Willie. Loading modules...


Error loading currency: No module named lxml (modules/currency.py:11)
Error loading weather: No module named lxml (modules/weather.py:16)
Error loading spellcheck: No module named enchant (modules/spellcheck.py:13)
Error loading bugzilla: No module named lxml (modules/bugzilla.py:11)


Registered 41 modules,
4 modules failed to load
...


However, I am having problems installing their dependencies:

$ sudo pip install tweepy
Downloading/unpacking tweepy
  Running setup.py egg_info for package tweepy
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/home/ant/.willie/build/tweepy/setup.py", line 17, in <module>
        install_reqs = parse_requirements('requirements.txt', session=uuid.uuid1())
    TypeError: parse_requirements() got an unexpected keyword argument 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/home/ant/.willie/build/tweepy/setup.py", line 17, in <module>

    install_reqs = parse_requirements('requirements.txt', session=uuid.uuid1())

TypeError: parse_requirements() got an unexpected keyword argument 'session'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/ant/.willie/build/tweepy
Storing complete log in /root/.pip/pip.log
$ sudo pip install lxml
Downloading/unpacking lxml
  Running setup.py egg_info for package lxml
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.4.2.
    Building without Cython.
    ERROR: /bin/sh: 1: xslt-config: not found

    ** make sure the development packages of libxml2 and libxslt are installed **

    Using build configuration of libxslt

Installing collected packages: lxml
  Running setup.py install for lxml
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.4.2.
    Building without Cython.
    ERROR: /bin/sh: 1: xslt-config: not found

    ** make sure the development packages of libxml2 and libxslt are installed **

    Using build configuration of libxslt
    building 'lxml.etree' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/home/ant/.willie/build/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
    src/lxml/lxml.etree.c:16:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools;__file__='/home/ant/.willie/build/lxml/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-D5xUo5-record/install-record.txt:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'

  warnings.warn(msg)

Building lxml version 3.4.2.

Building without Cython.

ERROR: /bin/sh: 1: xslt-config: not found



** make sure the development packages of libxml2 and libxslt are installed **



Using build configuration of libxslt

running install

running build

running build_py

copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-2.7/lxml/includes

running build_ext

building 'lxml.etree' extension

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/home/ant/.willie/build/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w

src/lxml/lxml.etree.c:16:20: fatal error: Python.h: No such file or directory

compilation terminated.

error: command 'gcc' failed with exit status 1

----------------------------------------
Command /usr/bin/python -c "import setuptools;__file__='/home/ant/.willie/build/lxml/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-D5xUo5-record/install-record.txt failed with error code 1 in /home/ant/.willie/build/lxml
Storing complete log in /root/.pip/pip.log
$ sudo pip install enchant
Downloading/unpacking enchant
  Could not find any downloads that satisfy the requirement enchant
No distributions at all found for enchant
Storing complete log in /root/.pip/pip.log
$ sudo pip install MySQLdb
Downloading/unpacking MySQLdb
  Real name of requirement MySQLdb is mysqldb
  Could not find any downloads that satisfy the requirement MySQLdb
No distributions at all found for MySQLdb
Storing complete log in /root/.pip/pip.log
$ sudo pip install mysqldb
Downloading/unpacking mysqldb
  Real name of requirement mysqldb is mysqldb
  Could not find any downloads that satisfy the requirement mysqldb
No distributions at all found for mysqldb
Storing complete log in /root/.pip/pip.log

**Comment by tyrope** [comment]
The problems you are having (installing lxml and enchant) are outside the scope of this project. If you want to enable -extras modules and they have issues as well, please report those [there](https://github.com/embolalia/willie-extras/issues/new).

**Comment by antdude** [comment]
OK and thanks. Is there a public forum for Willie stuff?
