### ISSUE TITLE
Meetbot: .subject breaks meetbot if special characters are used

### ISSUE THREAD

**Issue by vrecer** [embolalia/willie#753]
I've noticed that if you use special characters with .subject the meetbot breaks.
example ".subject ßč or something"
I've been running on version 5.0.0-gamma, but i've noticed that this has not yet been changed in later releases.

I've fixed it for myself with adding a logHTML_write function:
```python
def logHTML_write(item, channel):
    logfile = codecs.open(meeting_log_path + channel + '/' + figure_logfile_name(channel) + '.html', 'a', encoding='utf-8')
    logfile.write(item)
    logfile.close()
```

and changing this part (inside def meetingsubject):
```python
    logfile = open(meeting_log_path + trigger.sender + '/' + figure_logfile_name(trigger.sender) + '.html', 'a')
    logfile.write('</ul><h3>' + trigger.group(2) + '</h3><ul>')
    logfile.close()
```
with:
```python
   logHTML_write('</ul><h3>' + trigger.group(2) + '</h3><ul>',trigger.sender)
```
The problem is just that it does not open the html log file with codecs, and this fixed the problem for me.

**Comment by tyrope** [comment]
I think I spotted @embolalia testing this in our development channel earlier, Thank you for your report.
