### ISSUE TITLE
Unable to obtain op

### ISSUE THREAD

**Issue by rinzes** [embolalia/willie#754]
I am cfg as owner and willie has op. When I do .op I get KeyError: Identifier('dutch') (file "/usr/local/lib/python2.7/dist-packages/willie/modules/adminchannel.py", line 34, in op)

**Comment by tyrope** [comment]
Duplicate of issue #734, which is an issue you created and has been fixed. Please confirm you have updated to at least the commit that fixed this.

**Comment by rinzes** [comment]
I have upgraded to 5.1.1

**Comment by rinzes** [comment]
you can close this issue... I've been corrected in my understanding how this is suppose to work

**Comment by janandjohn3** [comment]
Just so I can look at why this is outputting a KeyError, can you tell us
the channel name you are running this in? Something may be screwing up the
checks for the privileges dict.

John Lage

**Comment by rinzes** [comment]
Irc.efnet.org #inews
