### ISSUE TITLE
Wikipedia links that are already url-encoded throw KeyError

### ISSUE THREAD

**Issue by ChaoticWeg** [embolalia/willie#755]
**Bug:** sending a Wikipedia URL that has already been URL-encoded to a channel containing an active willie bot causes the bot to spit out an error message instead of a blurb about the article

**Steps to reproduce:**

1. Visit a Wikipedia article with a URL containing a URL-unfriendly character ([example](http://en.wikipedia.org/wiki/L%C3%A9vy_flight))
2. Copy/paste the URL into chat, send message to channel (or PM to bot)

**Error thrown:** "KeyError: 'extract' (file "[willie-dir]/willie/modules/wikipedia.py", line 83, in mw_snippet)"

Apologies if this format is incorrect, this is the first issue I've posted.

**Comment by firerogue** [comment]
This is actually pretty good. If you could give us the version of willie
you are running and the full traceback that would be even better

**Comment by ChaoticWeg** [comment]
I don't readily have access to the version info or the traceback as I'm not the developer of the bot that gave the error, but I will find that info and report back ASAP.

**Comment by tyrope** [comment]
If the bot has the 'version' module loaded. ".version" should give you the output we'd like. :+1: on your current format so far, though. It's more than what we usually get. ^_^

**Comment by ChaoticWeg** [comment]
Ohp! v5.0.0-git is the version.

I still haven't been able to get my hands on a traceback yet, I'll see if I
can't ping the dev to paste it in a comment when they get the chance.

**Comment by tyrope** [comment]
Before you paste that, could you ask them to update the bot to 5.1.1 and see if it fixes things?

**Comment by flashcactus** [comment]
Updated the bot. Seems to be fixed (no error given for @ChaoticWeg's link, at least).

**Comment by ChaoticWeg** [comment]
Looks like that was the fix. Thanks for looking into it, @flashcactus @tyrope and @firerogue!
