### ISSUE TITLE
YouTube needs to use v3 API

### ISSUE THREAD

**Issue by embolalia** [embolalia/willie#764]
YouTube is killing the v2 API in a few weeks, so it'll be broken entirely if we don't move it over. If it requires an API key, we may have to kill the module entirely to conform with the guideline of not using modules that require API keys.

**Comment by elad661** [comment]
> we may have to kill the module entirely to conform with the guideline of not using modules that require API keys.

Is there such guideline though? `safety.py` and `github.py` require a API keys, for example

**Comment by embolalia** [comment]
`github.py` can still do url info without an API key, it just can't make or find issues. `safety.py` can still do Malwarebytes without an API key. If it provides some stuff without API keys, I'm fine with it, but I don't like things that have a hard requirement on a key to do anything to be in the default module set.

**Comment by kenjoe41** [comment]
Why can't we just leave it to the users to get there own API keys because even if you remove it from the main modules, others will code there own and use them.

**Comment by MyWay** [comment]
You should let the user choose, like kenjoe41 said, in my opinion.

**Comment by tyrope** [comment]
If we indeed do update it to v3 and want to keep the API key guideline, perhaps it's best then we move it to [-extras](https://github.com/embolalia/willie-extras).

**Comment by firerogue** [comment]
At this point we've dropped quite a few modules because of key
restrictions. Do we want to maybe consider opening a 3rd repo for
officially supported modules that require api keys? That way the
functionality would still exist, but it would still be possible to run
willie out of the box

**Comment by tyrope** [comment]
@firerogue Why a third repo? What's wrong with extras? We can always create a folder structure in it if it gets too messy.

Something like
```
API-Keys-required/github.py
API-Keys-required/youtube.py
Unmaintained/bucket.py
8ball.py
etc. etc.
```

**Comment by firerogue** [comment]
To allow people to get only the "official" packages, without the other
stuff in -extras. I guess its more relevant to OS/pip packaging than the
repo structure

**Comment by zwerxyplous** [comment]
Using the .yt command now returns this https://support.google.com/youtube/answer/6098135?p=yt_devicesupport&hl=en&rd=1

**Comment by falmic** [comment]
.yt sona almost viable
[YT Search] Title: https://youtube.com/devicesupport | Uploader: YouTube Help | Duration: 3mins 56secs | Uploaded: 17/04/2015, 15:23 | Views: 1,350,031 | Link: http://youtu.be/UKY3scPIMd8

**Comment by randomessence** [comment]
https://github.com/embolalia/willie/commit/0ca6aaf201608b6e937e5b2246a61a2286707970

So it is gone with no hope of fixing?

**Comment by tyrope** [comment]
@randomessence Unless somebody wants to rewrite it with the v3 API, and then it probably belongs in -extras due to the key requirement.

**Comment by flashcactus** [comment]
Hm, seems that at least the link title part of youtube.py does work properly: 

    11:54:31 < Lakel> https://www.youtube.com/watch?v=YMiNjHjpunU   progress' spin
    11:54:31 < Kountdown> [YouTube] Title: Russian Progress Spacecraft in Trouble! | Uploader: AbraxasSteadicam | Uploaded: 28/04/2015, 12:53 | Duration: 30secs | Views: 313,507 | Comments: 385 | Likes: 443 | Dislikes: 62

So maybe we can just use another search engine (google would be best, but it looks like it has API problems as well) to search the site and print info for the result?

**Comment by tyrope** [comment]
The link part doesn't work. Because the module no longer exists.
