### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by RustyBower** [embolalia/willie#768]
Issue:
[15:26:53]  USER:	thats…10.6mb per contact i have lolz
[15:26:54]  WILLIE:	UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 45: ordinal not in range(128) (file "/opt/willie/willie/modules/chanlogs.py", line 135, in log_message)

Problem:
            f.write(logline.encode('utf8')

Recommended Fix:
            f.write(logline.encode('utf8', 'replace')) or f.write(logline.encode('utf8', 'ignore'))

**Comment by teadur** [comment]
I tried both recommended fixes but doesnot seem to resolve the issue for me

**Comment by RustyBower** [comment]
Hey guys, 

I think I found the fix for this.

Line 135 in willie/modules/chanlogs.py
            +f.write(logline.encode('utf8'))
            +f.write(logline.decode('utf8').encode('utf8'))

**Comment by antdude** [comment]
Was this fixed for v5.3.0?

**Comment by emning** [comment]
No, @antdude, it was not. We just upgraded to 5.3.0 and started seeing this error on everything non-ascii.

The suggested fix from @RustyBower seems to work ok.

**Comment by antdude** [comment]
Thanks. I fixed my /usr/local/lib/python2.7/dist-packages/willie/modules/chanlogs.py file, restarted, and it worked! :)

**Comment by antdude** [comment]
Weird. Again with v5.4.0:
...
12:46PM <FngSaiYuk> Tarzan: tu es prêt
12:46PM <Willie> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 62:
          ordinal not in range(128) (file
          "/usr/local/lib/python2.7/dist-packages/willie/modules/chanlogs.py", line 135, in
          log_message)
12:47PM <FngSaiYuk> dang
12:47PM <FngSaiYuk> Willie doesn't like extended chars
...

**Comment by embolalia** [comment]
RSS module is removed in 6.0 and is no longer maintained, per #818. Closing.

**Comment by antdude** [comment]
Bah. The fix should still be implemented before v6. :P
