### ISSUE TITLE
Phpbb RSS Feed Error

### ISSUE THREAD

**Issue by akelling** [embolalia/willie#769]
Trying to add an rss feed from a phpbb version 3 forum and getting the following error:
TypeError: argument must be 9-item sequence, not None (file "/usr/home/irc/willie-5.2.0/willie/modules/rss.py", line 382, in read_feeds)

**Comment by tyrope** [comment]
Could you give us an example output of this phpBB rss feed? I have a suspicion it's a problem on their part, not on ours.

**Comment by akelling** [comment]
Willie v. 5.2.0 on FreeBSD10.1-RELEASE-p5 
I am running source.

**Comment by embolalia** [comment]
RSS module is removed in 6.0 and is no longer maintained. Closing.
