### ISSUE TITLE
Unicode Characters Posted in Chat Throw Errrr

### ISSUE THREAD

**Issue by slamanna212** [embolalia/willie#770]
Every time someone posts a unicode error we receive this error:

9:08 PM <•TrollOP> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 44: ordinal not in range(128) (file "/home/TrollOP/willie/willie/modules/chanlogs.py", line 135, in log_message)

**Comment by embolalia** [comment]
Duplicates #768.
