### ISSUE TITLE
Config file doesn't create even after it says it's created.

### ISSUE THREAD

**Issue by raxixor** [embolalia/willie#777]
It says "Config file written successfully.", but I can't find the config file anywhere, even after running Willie.

**Comment by tyrope** [comment]
It's in `~/.willie/`. If the config file cannot be created Willie should error out.

**Comment by raxixor** [comment]
I can't find it anywhere.

**Comment by raxixor** [comment]
Even with the search.

**Comment by raxixor** [comment]
nvm, found it. I had to google for a while.
