### ISSUE TITLE
Job() and JobSchedular() AttributeError

### ISSUE THREAD

**Issue by dman777** [embolalia/willie#778]
I'm not sure if I am doing this wrong. I am trying to use the Willie scheduler but I get ` AttributeError: 'function' object has no attribute 'thread'` from `bob.run()`:

```python
def dunno(bot):
    bot.say('Hello, world!')

@willie.module.commands('try')
def run_it(bot, trigger):
    bot.say('trying')
    jobb = bot.Job(2, dunno)
    bob = bot.JobScheduler(bot)
    bob.add_job(jobb)
    bob.run()
```

**Comment by embolalia** [comment]
What are you trying to do here? Maybe you want [`@interval`](http://willie.dftba.net/docs/#willie.module.interval)?

**Comment by dman777** [comment]
That is exactly what I wanted, thanks! Curious.... what is `Job() `and `JobScheduler()` for? Would `bot.msg()` be considered a job to run? From reading, I thought they would be giving the same end result as `interval`.

**Comment by firerogue** [comment]
Job() and JobScheduler() are the internals for how repeated tasks are
implemented in willie. @Interval() is how we expose that functionality to
module writers

**Comment by embolalia** [comment]
I'll remove those from the documentation for 6.0. I don't know why they were in the public documentation to begin with.

**Comment by dman777** [comment]
Thank you for clarifying! For the rest of the public documentation, are all the classes/methods public? If not, how can I differ between which is public and private?
