### ISSUE TITLE
config.homedir and config.dotdir undocumented and potentially inconsistent

### ISSUE THREAD

**Issue by matthijskooijman** [embolalia/willie#779]
On startup, the `homedir` and `dotdir` attributes are set on the config object, here: https://github.com/embolalia/willie/blob/master/willie.py#L151-L156

These attributes seem to be undocumented, but used in a few modules to store extra data. It seems both are intended to be equal (perhaps for backward compatibility somehow), but I'm not entirely sure.

Also, the code linked a above seems to not set the `homedir` attribute when a `homedir` value is explicitely specified in the code, it only sets the `homedir` global variable (which I think doesn't even need to be a global variable at all, btw).

Finally, the Config class duplicates the code above, by looking at the `self.core.homedir` config value directly, instead of just using `self.homedir` set by the code above:  https://github.com/embolalia/willie/blob/master/willie/config/__init__.py#L364-L368

**Comment by embolalia** [comment]
Yup. This is part of why #708 is a thing.

**Comment by embolalia** [comment]
Closing, since `config.core.dotdir` is removed in 6.0.
