### ISSUE TITLE
Upgrading Willie's Python v2.7 packages, without errors, go in a loop.

### ISSUE THREAD

**Issue by antdude** [embolalia/willie#792]
I always get these results:

$ sudo pip install --upgrade willie
Requirement already up-to-date: willie in /usr/local/lib/python2.7/dist-packages
Downloading/unpacking feedparser from https://pypi.python.org/packages/source/f/feedparser/feedparser-5.2.0.post1.tar.bz2#md5=9f54fe1e84412c16cdc5997d5b133a60 (from willie)
  Downloading feedparser-5.2.0.post1.tar.bz2 (192Kb): 192Kb downloaded
  Running setup.py egg_info for package feedparser

Requirement already up-to-date: pytz in /usr/local/lib/python2.7/dist-packages (from willie)
Requirement already up-to-date: lxml in /usr/local/lib/python2.7/dist-packages (from willie)
Requirement already up-to-date: praw in /usr/local/lib/python2.7/dist-packages (from willie)
Requirement already up-to-date: pyenchant in /usr/local/lib/python2.7/dist-packages (from willie)
Requirement already up-to-date: pygeoip in /usr/local/lib/python2.7/dist-packages (from willie)
Requirement already up-to-date: backports.ssl-match-hostname in /usr/local/lib/python2.7/dist-packages (from willie)
Requirement already up-to-date: requests>=2.3.0 in /usr/local/lib/python2.7/dist-packages (from praw->willie)
Requirement already up-to-date: six>=1.4 in /usr/local/lib/python2.7/dist-packages (from praw->willie)
Requirement already up-to-date: update-checker>=0.11 in /usr/local/lib/python2.7/dist-packages (from praw->willie)
Installing collected packages: feedparser
  Found existing installation: feedparser 5.2.0
    Uninstalling feedparser:
      Successfully uninstalled feedparser
  Running setup.py install for feedparser

Successfully installed feedparser
Cleaning up...

I am using Debian's stable. Thank you in advance. :)

**Comment by tyrope** [comment]
```Requirement already up-to-date: willie in /usr/local/lib/python2.7/dist-packages```
Sounds to me you're already running the latest (pip released) version of Willie and the log is all expected behaviour.

Please clarify what you expected to happen, and where exactly it went wrong?

**Comment by antdude** [comment]
Everytime I rerun "sudo pip install --upgrade willie" command, I get the same exact results. So, is my Willie and its dependencies really upgraded or not?

**Comment by tyrope** [comment]
You are already on the latest version. There's nothing to upgrade.

**Comment by antdude** [comment]
So, why does it keeps giving me updates when I rerun the command?

**Comment by firerogue** [comment]
It's not. Its building the dependancy tree, and cycling through it informing you that each one is up to date. Had one been behind it would have gotten updated, but since none of them are, none of them are getting updated.

**Comment by antdude** [comment]
Oh, interesting. It is sure confusing since I am used to apt-get commands. Thanks. :)
