### ISSUE TITLE
error with op, kick, ban, etc commands

### ISSUE THREAD

**Issue by falmic** [embolalia/willie#794]
<<1429728413.31 :Felek!~felek@Felek.users.quakenet.org PRIVMSG R2-D2 :.ban sharon
>>1429728413.31 PRIVMSG Felek :KeyError: Identifier('Felek') (file "/home/felek/Snakepit/willie/local/lib/python2.7/site-packages/willie/module.py", line 341
, in guarded)
<<1429728415.47 :Felek!~felek@Felek.users.quakenet.org PRIVMSG R2-D2 :.version
>>1429728415.48 PRIVMSG Felek :Felek: Willie v. 5.2.0

**Comment by janandjohn3** [comment]
Those commands must be done in a channel, not PM.

On Wednesday, April 22, 2015, falmic <notifications@github.com> wrote:

> <<1429728413.31 :Felek!~felek@Felek.users.quakenet.org
> <javascript:_e(%7B%7D,'cvml','felek@Felek.users.quakenet.org');> PRIVMSG
> R2-D2 :.ban sharon
>
>  1429728413.31 PRIVMSG Felek :KeyError: Identifier('Felek') (file
> "/home/felek/Snakepit/willie/local/lib/python2.7/site-packages/willie/module.py",
> line 341
> , in guarded)
> <<1429728415.47 :Felek!~felek@Felek.users.quakenet.org
> <javascript:_e(%7B%7D,'cvml','felek@Felek.users.quakenet.org');> PRIVMSG
> R2-D2 :.version
> 1429728415.48 PRIVMSG Felek :Felek: Willie v. 5.2.0
>
>  —
> Reply to this email directly or view it on GitHub
> <https://github.com/embolalia/willie/issues/794>.
>


-- 
John Lage

**Comment by falmic** [comment]
ye and both writer and bot must have OP on channel. now i know it. thx

**Comment by falmic** [comment]
ok, but still even on channel its doesent work

**Comment by janandjohn3** [comment]
Logs please? Also please make sure that both you and the bot have op in the
channel.

On Wednesday, April 22, 2015, falmic <notifications@github.com> wrote:

> ok, but still even on channel its doesent work
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/embolalia/willie/issues/794#issuecomment-95308397>.
>


-- 
John Lage

**Comment by falmic** [comment]
but doesent bot should lisen owne even when he dont have op?

**Comment by janandjohn3** [comment]
The bot doesn't work that way because the bot may be being used in a
channel that isn't run by the owner. If the bot was coded in that way a
channel takeover could occur.

On Wednesday, April 22, 2015, falmic <notifications@github.com> wrote:

> but doesent bot should lisen owne even when he dont have op?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/embolalia/willie/issues/794#issuecomment-95309432>.
>


-- 
John Lage

**Comment by falmic** [comment]
cuz for this situation i need bot. for example. i have temp op. my bot got full op
i got dc and how i have to get again op when bot dont lisen me?
sory for my english :/

**Comment by janandjohn3** [comment]
If I remember correctly Quakenet has channel services for that purpose. I
may be wrong, but if channel services is not available, Willie is not the
bot for that purpose.

On Wednesday, April 22, 2015, falmic <notifications@github.com> wrote:

> cuz for this situation i need bot. for example. i have temp op. my bot got
> full op
> i got dc and how i have to get again op when bot dont lisen me?
> sory for my english :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/embolalia/willie/issues/794#issuecomment-95310151>.
>


-- 
John Lage

**Comment by falmic** [comment]
oh crap, to bad :/

**Comment by falmic** [comment]
do you know maybe other with that functions?

**Comment by Ohcanep** [comment]
On QuakeNet you should request Q for your channel - it should do a better job of guarding the channel.
https://www.quakenet.org/help/q/how-do-i-request-q

**Comment by falmic** [comment]
yes, but for this i have to got 10+ ppl on same time and other things.
and Q will disapear when channel isnt use too much
thats why i need bot who will be keep channel and give ops

**Comment by falmic** [comment]
ok i make this on other way. just connect bot to znc and use bot commands and znc autoop. now works ;]
