### ISSUE TITLE
YT Search

### ISSUE THREAD

**Issue by falmic** [embolalia/willie#795]
<Felek> .yt sona almost viable
<R2-D2> [YT Search] Title: https://youtube.com/devicesupport | Uploader: YouTube Help | Duration: 3mins 56secs | Uploaded: 17/04/2015, 15:23 | Views: 1,350,031 | Link: http://youtu.be/UKY3scPIMd8

i know they change something on yotube api and now seach not work :/

**Comment by janandjohn3** [comment]
This is a duplicate of an issue I don't remember the number for.

On Wednesday, April 22, 2015, falmic <notifications@github.com> wrote:

> .yt sona almost viable
> [YT Search] Title: https://youtube.com/devicesupport | Uploader: YouTube
> Help | Duration: 3mins 56secs | Uploaded: 17/04/2015, 15:23 | Views:
> 1,350,031 | Link: http://youtu.be/UKY3scPIMd8
>
> i know they change something on yotube api and now seach not work :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/embolalia/willie/issues/795>.
>


-- 
John Lage

**Comment by falmic** [comment]
#764 ok sory ;]
