### ISSUE TITLE
Can't start willie

### ISSUE THREAD

**Issue by benjbubu** [embolalia/willie#803]
Hi everyone,

I got a problem with the last version (5.3.0) of willie.

I used pip install willie. Then when i launch it i got a problem with encoding but i handled it.

Now when i try to launch it i got this : 

Traceback (most recent call last):
 File "/usr/local/bin/willie", line 13, in <module>
  from willie.tools import stderr
File "/usr/local/lib/python2.7/dist-packages/willie/tools/__init__.py", line 47, in <module>
   from .time import get_timezone, format_time  # NOQA
 File "/usr/local/lib/python2.7/dist-packages/willie/tools/time.py", line 5, in <module>
 import datetime
ImportError: No module named datetime

I tried pip install datetime but i still got the error. When i try "pip freeze" i got the line DateTime == 4.0.1.

I don't know how to resolve this. Any idea ?

Thank you !

**Comment by embolalia** [comment]
[`datetime`](https://docs.python.org/2/library/datetime.html) is built in; you shouldn't need to install it. What OS are you on? What version of Python, and how did you get it? This looks like your environment is seriously messed up.

**Comment by benjbubu** [comment]
I actually using Debian 7 . i have several versions of python : 2.7and 3.2. Both have bern installed with aptitude. But my /usr/bon/python seems tout point the 2.7 version. But i dont know how to check it.

**Comment by n0ided** [comment]
Use python3 to start with python 3.x, python2 to start with 2.7

**Comment by embolalia** [comment]
@benjbubu do you get an error if you do `python -c 'import datetime'`? If you do, that's a Debian issue and you should file it with them. If you don't, I don't know. Are you doing something weird here? Like, removing things from wherever in `/usr` or messing with `$PYTHONPATH` or running on some wacky architecture? There's just nothing in Willie that would cause a standard module to be missing…

**Comment by benjbubu** [comment]
@embolalia so when i try your command i got an error no module datetime. I have the same message with python2.7 but no error if i do a python3 -c 'import datetime' (version 3.2)

**Comment by embolalia** [comment]
This means your Python 2 installation is messed up somehow. It's not related to Willie, so I'm closing this issue. You can try filing a bug with Debian, or going through whatever their support process is.
