### ISSUE TITLE
Youtube plugin broken (API change)

### ISSUE THREAD

**Issue by Flandre5carlet** [embolalia/willie#812]
Hey,

Since late April (I think) Youtube changed their API, and the current Youtube module always redirects to "youtube.com/devicesupport". Any way to fix that?

**Comment by janandjohn3** [comment]
I don't know what version of willie you have, but the youtube module has
been removed in recent versions of willie because of the API change.

John Lage

**Comment by Flandre5carlet** [comment]
Ah, okay. Must be an older version, then. Thanks.
