### ISSUE TITLE
Reddit.py - ValueError: Invalid format string

### ISSUE THREAD

**Issue by loliof** [embolalia/willie#816]
Using a fresh install of willie, I get the following anytime I post a reddit link:

Traceback (most recent call last):
  File "C:\Users\chris\Downloads\willie-master\willie\bot.py", line 459, in ca
ll
    exit_code = func(willie, trigger)
  File "C:\Users\chris\Downloads\willie-master\willie\modules\reddit.py", line
 85, in rpost_info
    trigger.sender, time_created)
  File "C:\Users\chris\Downloads\willie-master\willie\tools\time.py", line 104
, in format_time
    return time.strftime(tformat)
ValueError: Invalid format string

**Comment by embolalia** [comment]
Did the person posting the link or the channel they were posting it in have a timezone set? Do you have something set in `[core]` section of the config for `default_timezone`? My guess would be one of those, probably the latter, is set to something that isn't valid. I imagine `.t` would give the same error.

**Comment by loliof** [comment]
Guess that was it. My old version of willie was incredibly outdated, probably should have deleted the cfg and started from scratch. 

Thanks, closing this out.

**Comment by elad661** [comment]
This format string is invalid, see https://docs.python.org/2.7/library/datetime.html#strftime-strptime-behavior for details on allowed format characters.

**Comment by loliof** [comment]
The same thing happens even when it is changed to something like %H %M %S.

**Comment by embolalia** [comment]
`%F` is valid on Linux, but I'm guessing that's a platform-specific behavior of `strftime`. The default should be changed to `%Y-%m-%d` if that doesn't work on Windows.

**Comment by embolalia** [comment]
Fixed on master; will be released in 6.0.0.
