### ISSUE TITLE
Evaluate removing some modules

### ISSUE THREAD

**Issue by embolalia** [embolalia/willie#818]
I've written up some [guidelines](https://github.com/embolalia/willie/wiki/Module-inclusion-guidelines) on this, giving some of my thinking behind what should be required of modules. For 6.0, I'd like to clean up some of the more egregious violations, but I'd like to get some thoughts first. Obviously, since these are all open-source, anyone can cherry-pick them back (or just publish them to PyPI), but I'd like to consider getting them out of the main repo.

* `chanlogs` requires configuration. I don't know if it's widely used.
* `github` requires an API key, and is really pretty specifically geared toward the dftba.net instance of Willie.
* `radio` requires configuration, and is specific to ShoutCast.
* `rss` is the reason the guidelines include robustness. It's a constant pain in the ass, and someone else will undoubtedly do it better (and, ofc, we'll merge that in if they offer).

Are there others that we should consider axing?

**Comment by embolalia** [comment]
Those 4 have been removed in the 6.0 branch. I'll leave this open a bit longer for comment.

**Comment by iggy** [comment]
So are these going to be moved to willie-extras (or better yet some sort of module registry) or are we all left individually pulling an old version and forward-porting (hacking) our own copies?

**Comment by dgw** [comment]
For any of the modules here that are being dropped, it's very possible for other people to adopt any of them using `git filter-branch` tricks to extract them into new repositories that preserve the contribution/change history. From there, those forks could become part of a module registry or PyPI (I heard from @embolalia that 6.x will bring support for adding modules from PyPI).
