### ISSUE TITLE
Willie doesn't show title for links from sciencedaily.com

### ISSUE THREAD

**Issue by ivansandrk** [embolalia/willie#820]
Try it with eg. http://www.sciencedaily.com/releases/2015/06/150618134420.htm

I haven't looked into why it behaves this way, I'll poke around and see if I can figure it out when I get the time.

**Comment by dasu** [comment]
The website is protected by incapsula, the website will only render in a 'real' browser.  You can get around this by using selenium webdriver, although it may be a bit slow.

**Comment by embolalia** [comment]
In that case, the issue is on their end, not ours. Accounting for this edge case isn't worth introducing that complexity into an already over-complicated module.
