### ISSUE TITLE
UTF8 vs UTF-8

### ISSUE THREAD

**Issue by Kinematics** [embolalia/willie#821]
Attempting to use willie from Windows, Python 3.4.3

The coding cookie on all files is:

    # coding=utf8

However that causes it to fail on Windows, due to [this bug](https://bugs.python.org/issue20844), which has been open for over a year now.

Using

    # coding=utf-8

appears to fix the issue.  In other words, just don't use the shorthand form for UTF-8.

**Comment by embolalia** [comment]
I fucked up the commit message, but this is now fixed in master. It'll be released in 6.0.0.
