### ISSUE TITLE
Installation fails with " 'tuple' object has no attribute 'major' "

### ISSUE THREAD

**Issue by matiasw** [embolalia/willie#823]
Hi,
I'm trying to install willie on Linux Mint with `sudo pip install willie`, but the install fails with `AttributeError: 'tuple' object has no attribute 'major'` on 
<pre><code>
/build/willie/setup.py", line 18, in <module>
if sys.version_info.major < 3:
</pre></code>

Running `python` gives `Python 2.6.6 (r266:84292, Sep 15 2010, 15:52:39)`. I have `backports.ssl_match_hostname` installed.

**Comment by matiasw** [comment]
Welp, I ran 
`python2.7 setup.py egg_info
python2.7 setup.py install`
But, it does not complete and instead gives `src/lxml/lxml.etree.c:16: fatal error: Python.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1`

**Comment by embolalia** [comment]
Willie requires python 2.7. If you're on Mint and this isn't the default Python, you are multiple years out of date. The other problem is that lxml has dependencies if you install it from pip. The best way to fix this will be to update your distro, `apt-get install python-lxml; pip install willie`. Otherwise, follow [this](http://lxml.de/installation.html).

**Comment by matiasw** [comment]
I have python 2.7 (and 3) installed, as well as libxml, which is found during install:
<pre><code>Searching for lxml
Reading http://pypi.python.org/simple/lxml/
Best match: lxml 3.4.4</code></pre>
The problem comes later, with a missing `Python.h`. It looks like Python 2.7 does not include this file, for some reason:
<pre><code>sudo find / -name Python.h
/usr/include/python2.6/Python.h
/usr/include/python3.1/Python.h
ls /usr/include/python2.7/
pyconfig.h</code></pre>
Here is the whole error message:
<pre><code>Building against libxml2/libxslt in the following directory: /usr/lib
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
  warnings.warn(msg)
src/lxml/lxml.etree.c:16: fatal error: Python.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1</code></pre>
