### ISSUE TITLE
Steam module

### ISSUE THREAD

**Issue by Codered999** [embolalia/willie#833]
Consider adding a module to do basic things with Steam like search for a game or user.

.steam \<name of game OR app ID\>
.steam 440
would return something like
http://store.steampowered.com/app/440/ [Team Fortress 2 | Release Date: Oct 10, 2007 | User Reviews: Overwhelmingly Positive | Tags: Free to Play, Multiplayer, FPS, Action, Shooter...]

.steam \<steam username or community ID\>
.steam 76561198041880876
would return something like
https://steamcommunity.com/profiles/76561198041880876/ [Code | Level 21 | Status: Currently Online]

Currently running Willie v. 5.3.0 on Debian 8.1

**Comment by embolalia** [comment]
Does Steam have a public API for this? I can't seem to find one. If it does, does it require an API key?

**Comment by Codered999** [comment]
It does require an API key.
https://steamcommunity.com/dev
That sucks you don't want to take on modules that require API keys, not sure what you'll do about YT lol
