### ISSUE TITLE
Willie's release notes link is broken.

### ISSUE THREAD

**Issue by antdude** [embolalia/willie#839]
https://github.com/embolalia/willie/releases/tag/v5.4.1 is a 404 error/not found. :(
...
06:31PM [Willie(~willie@[deleted the address])] A new Willie version, 5.4.1, is available. I
am running 5.4.0. Please update me. Full release notes at
https://github.com/embolalia/willie/releases/tag/v5.4.1 - The project's name is changing with
version 6.0. The tentative new name is Sopel. Other suggestions can be made at
http://goo.gl/forms/f7AxcbOiTo and discussed in irc://irc.freenode.net/willie .
...

**Comment by embolalia** [comment]
Fixed.

**Comment by antdude** [comment]
What's the new URL since I already upgraded my Willie?
