### ISSUE TITLE
[admin] 5.4.1 can't set admins list from IRC

### ISSUE THREAD

**Issue by dgw** [embolalia/willie#841]
From PM:
````
<dgw> .set admins dgw,list,of,other,nicks
<willie> ValueError: ListAttribute value must be a list. (file
  "/usr/local/lib/python2.7/dist-packages/willie/config/types.py",
  line 224, in serialize)
````

**Comment by dgw** [comment]
Tracked this down to the admin module, as that's where the `.set` command is defined. But it might be considered core anyway as the exception is thrown in `config/types.py`.

**Comment by embolalia** [comment]
The issue is [here](https://github.com/embolalia/willie/blob/master/willie/modules/admin.py#L202). `value` is still a string at this point, and setting a config attribute to a string is not always valid.

**Comment by dgw** [comment]
I'll look into this again tonight. Hopefully I can track down a way to solve it generically no matter what the option type (as long as the option type defines a `parse()` method).

**Comment by dgw** [comment]
Followed code around in circles to no avail. I just couldn't find a way to access the value type and call `.parse()`, instead of getting the attribute value.

**Comment by embolalia** [comment]
Yeah, it involves a bit of magic to get the descriptor rather than the value (because descriptors themselves are kind of magic). It's fixed now.

**Comment by dgw** [comment]
I see some of the magic. Thanks for the fix, and I'll try to learn from it.
